language: node_js
env:
  -CI=false
cache: 
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build:ghpages
  - npm run coverage
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
